# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "Microsoft.Extensions.Logging.Abstractions"; version = "7.0.1"; hash = "sha256-05mravm6SK0wNV3BKDTmN+8/1RxcPOM9kaUvGhjWY3c="; })
  (fetchNuGet { pname = "Microsoft.VisualStudio.Azure.Containers.Tools.Targets"; version = "1.21.0"; hash = "sha256-umtCr5DOLI0PqpXhIWg1C1LLiurCt5dEfs6d+4G6HcU="; })
  (fetchNuGet { pname = "MySqlConnector"; version = "2.3.7"; hash = "sha256-J5/f9jxC7atuVw9aCcak1weoQwaKt4krUf86E4aAJPE="; })
]
